# site-specific details
title: Babycastles
description: >
  Babycastles is a collective with roots in New York's D.I.Y. culture dedicated
  to building platforms for diversity in video games culture at every level from
  creators to consumers, connecting the independent game developer community
  with the broader New York art community, identifying exciting new voices in
  game creation from around the world and providing them exposure to new
  audiences.

# site url details
url: "https://babycastles.github.io"
baseurl: ""

# site-wide contact details
email:            meow@babycastles.com
twitter_username: babycastles
github_username:  babycastles

# build settings
port:        5000
theme:       jekyll-theme-cayman
highlighter: rouge
markdown:    kramdown
permalink:   pretty
exclude:
  - vendor

collections:
  user:
    output: true
    permalink: /user/:path/

defaults:
  -
    scope:
      path: ""
      type: user
    values:
      layout: user
